apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fireresponse
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fireresponse
    spec:
      containers:
      # - name: worker
      #   imagePullPolicy: Always
      #   image: gcr.io/opszero-173723/fireresponse:c72a8cbe8c90f137d7291e6f99ea923f411e7ed0-2017-10-12-22-16-20
      #   command: ["./server.sh"]
      - name: fireresponse
        image: gcr.io/opszero-173723/fireresponse:c72a8cbe8c90f137d7291e6f99ea923f411e7ed0-2017-10-12-22-16-20
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: fireresponse
spec:
  type: LoadBalancer
  selector:
    app: fireresponse
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
